//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deviss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Contents { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ClosetNo { get; set; }
    
        public virtual Closet Closet { get; set; }
        public virtual Device Device { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual User User { get; set; }
    }
}
